[project]
name = "pdf-summarize"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "google-genai>=1.18.0",
    "openai>=1.84.0",
    "pymupdf>=1.26.0",
]
